<?php


namespace App\Form;


use App\data\SearcheData;
use App\Entity\Campus;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       $builder

           ->add('campus', EntityType::class,[
               'choice_label' =>'nom',
               'class'=>Campus::class,
               'required'=>false,
               'placeholder'=>'choisir un campus'
             ])

           ->add('q', TextType::class, [
               'label'=>'le nom de la sortie contient',
               'required'=>false,
               'attr'=>[
                   'placeholder'=> 'Rechercher une sortie'
               ]
           ])

           ->add('dated', DateType::class, [
               'label'=>'Entre ',
               'required'=>false,
               'widget' => 'single_text',
               'attr' => ['class' => 'js-datepicker']
           ])
           ->add('datef', DateType::class, [
               'label'=>'et ',
               'required'=>false,
               'widget' => 'single_text',
               'attr' => ['class' => 'js-datepicker']
           ])

           ->add('user', CheckboxType::class, [
               'label'    => 'Sortie dont je suis l\'organisateur/trice',
               'required' => false,
           ])
           ->add('user1', CheckboxType::class, [
               'label'    => 'Sorties auxquelles je suis inscrit/e',
               'required' => false,
           ])
           ->add('user2', CheckboxType::class, [
               'label'    => 'Sorties auxquelles je ne suis pas inscrit/e',
               'required' => false,
           ])
           ->add('user3', CheckboxType::class, [
               'label'    => 'Sorties passées',
               'required' => false,
           ])

       ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'data_class' => SearcheData::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }
    public function getBlockPrefix()
    {
            return '';
    }

}