<?php


namespace App\Form;


use App\data\SearcheCampus;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchCampVilForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       $builder



           ->add('q', TextType::class, [
               'label'=>'le nom  contient',
               'required'=>false,
               'attr'=>[
                   'placeholder'=> 'taper votre recherche'
               ]
           ])


       ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'data_class' => SearcheCampus::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }
    public function getBlockPrefix()
    {
            return '';
    }

}